# Minimal Win9x DirectDraw 32-bit initialization bridge.
# Target toolchain: Microsoft Visual C++ 6.0 / LINK 6.x.

CC=cl
LD=link
CFLAGS=/nologo /O1 /W3 /Zl
LDFLAGS=/nologo /DLL /NODEFAULTLIB /ENTRY:DllMain@12 /BASE:0xA1000000 /FIXED:NO /SUBSYSTEM:WINDOWS,4.0 /SECTION:.text,ERS /SECTION:.rdata,RS /SECTION:.data,RWS /SECTION:.npddshr,RWS /DEF:NPDISPDD.DEF

all: NPDISPDD.DLL

NPDISPDD.OBJ: npdispdd.c
	$(CC) $(CFLAGS) /c npdispdd.c

NPDISPDD.DLL: NPDISPDD.OBJ NPDISPDD.DEF
	$(LD) $(LDFLAGS) /OUT:NPDISPDD.DLL NPDISPDD.OBJ

clean:
	-del NPDISPDD.OBJ
	-del NPDISPDD.DLL
	-del NPDISPDD.EXP
	-del NPDISPDD.LIB
