typedef unsigned long DWORD;
typedef int BOOL;

#ifndef WINAPI
#define WINAPI __stdcall
#endif

#define DLL_PROCESS_ATTACH 1

#define NPDISP_DDHALINFO_DDCALLBACKS       4
#define NPDISP_DDHALINFO_SURFACECALLBACKS  8
#define NPDISP_DDHALINFO_PALETTECALLBACKS  12
#define NPDISP_DDHALINFO_GETDRIVERINFO      416
#define NPDISP_DDHALINFO_HINSTANCE          444
#define NPDISP_DDHALINFO_BRIDGE_MAGIC       448
#define NPDISP_DDHALINFO_BRIDGE_VERSION     452
#define NPDISP_DDHALINFO_BRIDGE_FEATURES    456

#define NPDISP_DDCALLBACKS_SIZE              48
#define NPDISP_DDCALLBACKS_FLAGS              4
#define NPDISP_DDCALLBACKS_CREATESURFACE     12
#define NPDISP_DDCALLBACKS_SETCOLORKEY       16
#define NPDISP_DDCALLBACKS_SETMODE           20
#define NPDISP_DDCALLBACKS_WAITVB            24
#define NPDISP_DDCALLBACKS_CANCREATESURFACE  28
#define NPDISP_DDCALLBACKS_CREATEPALETTE     32
#define NPDISP_DDCALLBACKS_GETSCANLINE       36
#define NPDISP_DDCALLBACKS_SETEXCLUSIVEMODE  40
#define NPDISP_DDCALLBACKS_FLIPTOGDI         44

#define NPDISP_DDHAL_CB32_CREATESURFACE      0x00000002UL
#define NPDISP_DDHAL_CB32_SETCOLORKEY        0x00000004UL
#define NPDISP_DDHAL_CB32_SETMODE            0x00000008UL
#define NPDISP_DDHAL_CB32_WAITVB             0x00000010UL
#define NPDISP_DDHAL_CB32_CANCREATESURFACE   0x00000020UL
#define NPDISP_DDHAL_CB32_CREATEPALETTE      0x00000040UL
#define NPDISP_DDHAL_CB32_GETSCANLINE        0x00000080UL
#define NPDISP_DDHAL_CB32_SETEXCLUSIVEMODE   0x00000100UL
#define NPDISP_DDHAL_CB32_FLIPTOGDI          0x00000200UL
#define NPDISP_DDHAL_CB32_SUPPORTED          0x000003FEUL

#define NPDISP_DDSURFACECALLBACKS_SIZE        64
#define NPDISP_DDSURFACECALLBACKS_FLAGS        4
#define NPDISP_DDSURFACECALLBACKS_DESTROY      8
#define NPDISP_DDSURFACECALLBACKS_FLIP        12
#define NPDISP_DDSURFACECALLBACKS_SETCLIPLIST 16
#define NPDISP_DDSURFACECALLBACKS_LOCK        20
#define NPDISP_DDSURFACECALLBACKS_UNLOCK      24
#define NPDISP_DDSURFACECALLBACKS_BLT         28
#define NPDISP_DDSURFACECALLBACKS_SETCOLORKEY 32
#define NPDISP_DDSURFACECALLBACKS_ADDATTACHED 36
#define NPDISP_DDSURFACECALLBACKS_GETBLTSTATUS 40
#define NPDISP_DDSURFACECALLBACKS_GETFLIPSTATUS 44
#define NPDISP_DDSURFACECALLBACKS_UPDATEOVERLAY 48
#define NPDISP_DDSURFACECALLBACKS_SETOVERLAYPOS 52
#define NPDISP_DDSURFACECALLBACKS_SETPALETTE  60

#define NPDISP_DDHAL_SURFCB32_DESTROY          0x00000001UL
#define NPDISP_DDHAL_SURFCB32_FLIP             0x00000002UL
#define NPDISP_DDHAL_SURFCB32_SETCLIPLIST      0x00000004UL
#define NPDISP_DDHAL_SURFCB32_LOCK             0x00000008UL
#define NPDISP_DDHAL_SURFCB32_UNLOCK           0x00000010UL
#define NPDISP_DDHAL_SURFCB32_BLT              0x00000020UL
#define NPDISP_DDHAL_SURFCB32_SETCOLORKEY      0x00000040UL
#define NPDISP_DDHAL_SURFCB32_ADDATTACHED      0x00000080UL
#define NPDISP_DDHAL_SURFCB32_GETBLTSTATUS     0x00000100UL
#define NPDISP_DDHAL_SURFCB32_GETFLIPSTATUS    0x00000200UL
#define NPDISP_DDHAL_SURFCB32_UPDATEOVERLAY    0x00000400UL
#define NPDISP_DDHAL_SURFCB32_SETOVERLAYPOS    0x00000800UL
#define NPDISP_DDHAL_SURFCB32_SETPALETTE       0x00002000UL
#define NPDISP_DDHAL_SURFCB32_SUPPORTED        0x00002FFFUL

#define NPDISP_DDPALETTECALLBACKS_SIZE          16
#define NPDISP_DDPALETTECALLBACKS_FLAGS          4
#define NPDISP_DDPALETTECALLBACKS_DESTROY        8
#define NPDISP_DDPALETTECALLBACKS_SETENTRIES    12
#define NPDISP_DDHAL_PALCB32_DESTROY            0x00000001UL
#define NPDISP_DDHAL_PALCB32_SETENTRIES         0x00000002UL
#define NPDISP_DDHAL_PALCB32_SUPPORTED          0x00000003UL

#define NPDISP_DDBRIDGE_REQUEST_MAGIC            0x4444504eUL /* "NPDD" */
#define NPDISP_DDBRIDGE_ACK_MAGIC                0x4b4f4444UL /* "DDOK" */
#define NPDISP_DDBRIDGE_ABI_VERSION              0x00010000UL
#define NPDISP_DDBRIDGE_FEATURE_GETDRIVERINFO    0x00000001UL
#define NPDISP_DDBRIDGE_FEATURE_SUPPORTED        NPDISP_DDBRIDGE_FEATURE_GETDRIVERINFO

#define NPDISP_EXEC_MAGIC_LOW                    0x0000504eUL
#define NPDISP_EXEC_PORT                         0x07e9
#define NPDISP_EXEC_COMMAND                      0x46
#define NPDISP_FUNCORDER_DD32_DISPATCH           0xfe30UL

/* 固定2DブリッジではEDIにコールバックIDを渡す。 */
#define NPDISP_DDBRIDGE_CB_DD_CREATESURFACE      0x0001UL
#define NPDISP_DDBRIDGE_CB_DD_SETCOLORKEY        0x0002UL
#define NPDISP_DDBRIDGE_CB_DD_SETMODE            0x0003UL
#define NPDISP_DDBRIDGE_CB_DD_WAITVB             0x0004UL
#define NPDISP_DDBRIDGE_CB_DD_CANCREATESURFACE   0x0005UL
#define NPDISP_DDBRIDGE_CB_DD_CREATEPALETTE      0x0006UL
#define NPDISP_DDBRIDGE_CB_DD_GETSCANLINE        0x0007UL
#define NPDISP_DDBRIDGE_CB_DD_SETEXCLUSIVEMODE   0x0008UL
#define NPDISP_DDBRIDGE_CB_DD_FLIPTOGDI          0x0009UL
#define NPDISP_DDBRIDGE_CB_DD_GETDRIVERINFO      0x000aUL

#define NPDISP_DDBRIDGE_CB_SURF_DESTROY           0x0100UL
#define NPDISP_DDBRIDGE_CB_SURF_FLIP              0x0101UL
#define NPDISP_DDBRIDGE_CB_SURF_SETCLIPLIST       0x0102UL
#define NPDISP_DDBRIDGE_CB_SURF_LOCK              0x0103UL
#define NPDISP_DDBRIDGE_CB_SURF_UNLOCK            0x0104UL
#define NPDISP_DDBRIDGE_CB_SURF_BLT               0x0105UL
#define NPDISP_DDBRIDGE_CB_SURF_SETCOLORKEY       0x0106UL
#define NPDISP_DDBRIDGE_CB_SURF_ADDATTACHED       0x0107UL
#define NPDISP_DDBRIDGE_CB_SURF_GETBLTSTATUS      0x0108UL
#define NPDISP_DDBRIDGE_CB_SURF_GETFLIPSTATUS     0x0109UL
#define NPDISP_DDBRIDGE_CB_SURF_UPDATEOVERLAY     0x010aUL
#define NPDISP_DDBRIDGE_CB_SURF_SETOVERLAYPOS     0x010bUL
#define NPDISP_DDBRIDGE_CB_SURF_SETPALETTE        0x010dUL

#define NPDISP_DDBRIDGE_CB_PAL_DESTROY             0x0200UL
#define NPDISP_DDBRIDGE_CB_PAL_SETENTRIES          0x0201UL

/*
 * Win9xのDirectDrawはHAL DLLを共有アドレス領域へロードするため、
 * プロセス間で使用する状態は共有セクションに置く。
 */
#pragma data_seg(".npddshr")
static DWORD npdispdd_hInstance = 0xFFFFFFFFUL;
#pragma data_seg()

/*
 * 2DコールバックはESIにLPDDHAL_*DATA、EDIにコールバックIDを設定して
 * np21/wへ転送する。戻り値はEAXのDDHAL_DRIVER_*。
 */
static DWORD npdispdd_host_call(DWORD callbackId, void *lpData)
{
    DWORD result;

    __asm {
        push ebx
        push esi
        push edi
        mov  ebx, NPDISP_FUNCORDER_DD32_DISPATCH
        mov  esi, lpData
        mov  edi, callbackId
        mov  ecx, NPDISP_EXEC_MAGIC_LOW
        mov  dx, NPDISP_EXEC_PORT
        mov  al, NPDISP_EXEC_COMMAND
        out  dx, al
        mov  result, eax
        pop  edi
        pop  esi
        pop  ebx
    }
    return result;
}

#define NPDISP_DDBRIDGE_WRAPPER(name, id) \
    static DWORD WINAPI name(void *lpData) { return npdispdd_host_call((id), lpData); }

NPDISP_DDBRIDGE_WRAPPER(npdispdd_CreateSurface,       NPDISP_DDBRIDGE_CB_DD_CREATESURFACE)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_DriverSetColorKey,   NPDISP_DDBRIDGE_CB_DD_SETCOLORKEY)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_SetMode,             NPDISP_DDBRIDGE_CB_DD_SETMODE)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_WaitForVerticalBlank,NPDISP_DDBRIDGE_CB_DD_WAITVB)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_CanCreateSurface,    NPDISP_DDBRIDGE_CB_DD_CANCREATESURFACE)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_CreatePalette,       NPDISP_DDBRIDGE_CB_DD_CREATEPALETTE)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_GetScanLine,         NPDISP_DDBRIDGE_CB_DD_GETSCANLINE)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_SetExclusiveMode,    NPDISP_DDBRIDGE_CB_DD_SETEXCLUSIVEMODE)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_FlipToGDISurface,    NPDISP_DDBRIDGE_CB_DD_FLIPTOGDI)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_GetDriverInfo,       NPDISP_DDBRIDGE_CB_DD_GETDRIVERINFO)

NPDISP_DDBRIDGE_WRAPPER(npdispdd_DestroySurface,      NPDISP_DDBRIDGE_CB_SURF_DESTROY)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_Flip,                NPDISP_DDBRIDGE_CB_SURF_FLIP)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_SetClipList,         NPDISP_DDBRIDGE_CB_SURF_SETCLIPLIST)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_Lock,                NPDISP_DDBRIDGE_CB_SURF_LOCK)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_Unlock,              NPDISP_DDBRIDGE_CB_SURF_UNLOCK)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_Blt,                 NPDISP_DDBRIDGE_CB_SURF_BLT)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_SetColorKey,         NPDISP_DDBRIDGE_CB_SURF_SETCOLORKEY)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_AddAttachedSurface,  NPDISP_DDBRIDGE_CB_SURF_ADDATTACHED)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_GetBltStatus,        NPDISP_DDBRIDGE_CB_SURF_GETBLTSTATUS)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_GetFlipStatus,       NPDISP_DDBRIDGE_CB_SURF_GETFLIPSTATUS)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_UpdateOverlay,       NPDISP_DDBRIDGE_CB_SURF_UPDATEOVERLAY)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_SetOverlayPosition,  NPDISP_DDBRIDGE_CB_SURF_SETOVERLAYPOS)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_SetPalette,          NPDISP_DDBRIDGE_CB_SURF_SETPALETTE)

NPDISP_DDBRIDGE_WRAPPER(npdispdd_DestroyPalette,      NPDISP_DDBRIDGE_CB_PAL_DESTROY)
NPDISP_DDBRIDGE_WRAPPER(npdispdd_SetEntries,          NPDISP_DDBRIDGE_CB_PAL_SETENTRIES)

#define NPDISP_DDBRIDGE_INSTALL(table, request, bit, offset, fn) \
    do { if ((request) & (bit)) *(DWORD *)((table) + (offset)) = (DWORD)(fn); } while (0)

/*
 * dwContextは共有DDHALINFOのフラットアドレス。np21/wが要求した
 * 2DコールバックだけをDirectDrawへ登録する。
 */
DWORD WINAPI DriverInit(DWORD dwContext)
{
    unsigned char *sharedInfo;
    unsigned char *ddCallbacks;
    unsigned char *surfaceCallbacks;
    unsigned char *paletteCallbacks;
    DWORD ddRequest;
    DWORD surfaceRequest;
    DWORD paletteRequest;
    DWORD features;

    if (!dwContext || !npdispdd_hInstance || npdispdd_hInstance == 0xFFFFFFFFUL) {
        return 0;
    }

    sharedInfo = (unsigned char *)dwContext;
    if (*(DWORD *)(sharedInfo + NPDISP_DDHALINFO_BRIDGE_MAGIC) != NPDISP_DDBRIDGE_REQUEST_MAGIC ||
        *(DWORD *)(sharedInfo + NPDISP_DDHALINFO_BRIDGE_VERSION) != NPDISP_DDBRIDGE_ABI_VERSION) {
        return 0;
    }

    features = *(DWORD *)(sharedInfo + NPDISP_DDHALINFO_BRIDGE_FEATURES);
    if (features & ~NPDISP_DDBRIDGE_FEATURE_SUPPORTED) {
        return 0;
    }

    ddCallbacks = (unsigned char *)(*(DWORD *)(sharedInfo + NPDISP_DDHALINFO_DDCALLBACKS));
    surfaceCallbacks = (unsigned char *)(*(DWORD *)(sharedInfo + NPDISP_DDHALINFO_SURFACECALLBACKS));
    paletteCallbacks = (unsigned char *)(*(DWORD *)(sharedInfo + NPDISP_DDHALINFO_PALETTECALLBACKS));
    if (!ddCallbacks || !surfaceCallbacks || !paletteCallbacks) {
        return 0;
    }
    if (*(DWORD *)(ddCallbacks + 0) != NPDISP_DDCALLBACKS_SIZE ||
        *(DWORD *)(surfaceCallbacks + 0) != NPDISP_DDSURFACECALLBACKS_SIZE ||
        *(DWORD *)(paletteCallbacks + 0) != NPDISP_DDPALETTECALLBACKS_SIZE) {
        return 0;
    }

    ddRequest = *(DWORD *)(ddCallbacks + NPDISP_DDCALLBACKS_FLAGS);
    surfaceRequest = *(DWORD *)(surfaceCallbacks + NPDISP_DDSURFACECALLBACKS_FLAGS);
    paletteRequest = *(DWORD *)(paletteCallbacks + NPDISP_DDPALETTECALLBACKS_FLAGS);
    if ((ddRequest & ~NPDISP_DDHAL_CB32_SUPPORTED) ||
        (surfaceRequest & ~NPDISP_DDHAL_SURFCB32_SUPPORTED) ||
        (paletteRequest & ~NPDISP_DDHAL_PALCB32_SUPPORTED)) {
        return 0;
    }

    /* DestroyDriverはlpSetInfoの寿命をNPDISP.DRV側で管理するため16bit側に残す。 */
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_CREATESURFACE,     NPDISP_DDCALLBACKS_CREATESURFACE,    npdispdd_CreateSurface);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_SETCOLORKEY,       NPDISP_DDCALLBACKS_SETCOLORKEY,      npdispdd_DriverSetColorKey);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_SETMODE,           NPDISP_DDCALLBACKS_SETMODE,          npdispdd_SetMode);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_WAITVB,            NPDISP_DDCALLBACKS_WAITVB,           npdispdd_WaitForVerticalBlank);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_CANCREATESURFACE,  NPDISP_DDCALLBACKS_CANCREATESURFACE, npdispdd_CanCreateSurface);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_CREATEPALETTE,     NPDISP_DDCALLBACKS_CREATEPALETTE,    npdispdd_CreatePalette);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_GETSCANLINE,       NPDISP_DDCALLBACKS_GETSCANLINE,      npdispdd_GetScanLine);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_SETEXCLUSIVEMODE,  NPDISP_DDCALLBACKS_SETEXCLUSIVEMODE, npdispdd_SetExclusiveMode);
    NPDISP_DDBRIDGE_INSTALL(ddCallbacks, ddRequest, NPDISP_DDHAL_CB32_FLIPTOGDI,         NPDISP_DDCALLBACKS_FLIPTOGDI,        npdispdd_FlipToGDISurface);

    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_DESTROY,       NPDISP_DDSURFACECALLBACKS_DESTROY,       npdispdd_DestroySurface);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_FLIP,          NPDISP_DDSURFACECALLBACKS_FLIP,          npdispdd_Flip);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_SETCLIPLIST,   NPDISP_DDSURFACECALLBACKS_SETCLIPLIST,   npdispdd_SetClipList);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_LOCK,          NPDISP_DDSURFACECALLBACKS_LOCK,          npdispdd_Lock);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_UNLOCK,        NPDISP_DDSURFACECALLBACKS_UNLOCK,        npdispdd_Unlock);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_BLT,           NPDISP_DDSURFACECALLBACKS_BLT,           npdispdd_Blt);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_SETCOLORKEY,   NPDISP_DDSURFACECALLBACKS_SETCOLORKEY,   npdispdd_SetColorKey);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_ADDATTACHED,   NPDISP_DDSURFACECALLBACKS_ADDATTACHED,   npdispdd_AddAttachedSurface);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_GETBLTSTATUS,  NPDISP_DDSURFACECALLBACKS_GETBLTSTATUS,  npdispdd_GetBltStatus);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_GETFLIPSTATUS, NPDISP_DDSURFACECALLBACKS_GETFLIPSTATUS, npdispdd_GetFlipStatus);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_UPDATEOVERLAY, NPDISP_DDSURFACECALLBACKS_UPDATEOVERLAY, npdispdd_UpdateOverlay);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_SETOVERLAYPOS, NPDISP_DDSURFACECALLBACKS_SETOVERLAYPOS, npdispdd_SetOverlayPosition);
    NPDISP_DDBRIDGE_INSTALL(surfaceCallbacks, surfaceRequest, NPDISP_DDHAL_SURFCB32_SETPALETTE,     NPDISP_DDSURFACECALLBACKS_SETPALETTE,    npdispdd_SetPalette);

    NPDISP_DDBRIDGE_INSTALL(paletteCallbacks, paletteRequest, NPDISP_DDHAL_PALCB32_DESTROY,    NPDISP_DDPALETTECALLBACKS_DESTROY,    npdispdd_DestroyPalette);
    NPDISP_DDBRIDGE_INSTALL(paletteCallbacks, paletteRequest, NPDISP_DDHAL_PALCB32_SETENTRIES, NPDISP_DDPALETTECALLBACKS_SETENTRIES, npdispdd_SetEntries);

    if (features & NPDISP_DDBRIDGE_FEATURE_GETDRIVERINFO) {
        *(DWORD *)(sharedInfo + NPDISP_DDHALINFO_GETDRIVERINFO) = (DWORD)npdispdd_GetDriverInfo;
    }

    *(DWORD *)(sharedInfo + NPDISP_DDHALINFO_HINSTANCE) = npdispdd_hInstance;
    *(DWORD *)(sharedInfo + NPDISP_DDHALINFO_BRIDGE_MAGIC) = NPDISP_DDBRIDGE_ACK_MAGIC;
    return 1;
}

BOOL WINAPI DllMain(void *hInstance, DWORD reason, void *reserved)
{
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        npdispdd_hInstance = (DWORD)hInstance;
    }
    return 1;
}
