#-------------------------------------------
# Neko Project II Display Driver Makefile
#-------------------------------------------

NAME      = NPDISP
O         = N_OBJ

RES12DIR  = ..\12_RES
RES16DIR  = ..\16_RES
RESFILE   = $(RES12DIR)\12_RES.res

MOPT      = -ML -W2 -T
RCOPT     = -DDBCS -DJAPAN
INCS      = -I. -I..
LINK      = link $(LOPT)/NOE/NOD/LI/MAP/AL:16
ASM       = masm $(MOPT) $(INCS)
RASM      = masm -b63 -t -v -z

# ’·‚·‚¬‚ÄƒGƒ‰[‚É‚È‚é‚Ì‚ð‰ñ”ð 
OBJ1 = npdisp.obj bitblt.obj bmc_main.obj charwdth.obj colorinf.obj control.obj
OBJ2 = cursor.obj disable.obj discreen.obj enable.obj enum.obj fb.obj
OBJ3 = output.obj pixel.obj robject.obj scanlr.obj setmode.obj svscreen.obj
OBJ4 = textout.obj sswitch.obj int2f.obj sblt.obj setpal.obj getpal.obj
OBJ5 = setpalt.obj getpalt.obj updcol.obj selbmp.obj bmpbits.obj sdib.obj

OBJ = $(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4) $(OBJ5)

RESBIN12 = $(RES12DIR)\config.bin $(RES12DIR)\clrtable.bin $(RES12DIR)\fonts.bin
RESBIN16 = $(RES16DIR)\config.bin $(RES16DIR)\fonts.bin

all: res $(NAME).drv

res: $(RES12DIR)\$(NAME).mrk
	copy $(NAME).rcv $(RES12DIR)\display.rcv

$(RES12DIR)\$(NAME).mrk:
	del $(RES12DIR)\*.mrk
	del $(RES12DIR)\*.res
	echo $(NAME) > $(RES12DIR)\$(NAME).mrk

# .asm -> .obj
npdisp.obj: ..\npdisp.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
bitblt.obj: ..\bitblt.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
bmc_main.obj: ..\bmc_main.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
charwdth.obj: ..\charwdth.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
colorinf.obj: ..\colorinf.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
control.obj: ..\control.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
cursor.obj: ..\cursor.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
disable.obj: ..\disable.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
discreen.obj: ..\discreen.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
enable.obj: ..\enable.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
enum.obj: ..\enum.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
fb.obj: ..\fb.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
output.obj: ..\output.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
pixel.obj: ..\pixel.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
robject.obj: ..\robject.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
scanlr.obj: ..\scanlr.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
setmode.obj: ..\setmode.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
svscreen.obj: ..\svscreen.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
textout.obj: ..\textout.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
sswitch.obj: ..\sswitch.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
int2f.obj: ..\int2f.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
sblt.obj: ..\sblt.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
setpal.obj: ..\setpal.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
getpal.obj: ..\getpal.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
setpalt.obj: ..\setpalt.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
getpalt.obj: ..\getpalt.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
updcol.obj: ..\updcol.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
selbmp.obj: ..\selbmp.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
bmpbits.obj: ..\bmpbits.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;
sdib.obj: ..\sdib.asm ..\npdisp.inc
	$(ASM) ..\$*,$@;


$(RES12DIR)\12_RES.res: $(RES12DIR)\12_RES.rc $(RES12DIR)\*.bmp $(RES16DIR)\*.bmp $(NAME).rcv
	cd $(RES12DIR)
	RC $(RCOPT) -r 12_RES.rc 12_RES.res
	cd ..\$(O)

$(NAME).drv: $(NAME).def $(OBJ) $(RESFILE)
	$(LINK) @<<
$(OBJ1)+
$(OBJ2)+
$(OBJ3)+
$(OBJ4)+
$(OBJ5)
$(NAME).drv
$(NAME).map
libw
$(NAME).def
<<
	rc -b -30 $(RESFILE) $(NAME).drv
	copy $(NAME).map display.map
	-mapsym /n display
	-del $(NAME).sym
	rename display.sym $(NAME).sym

clean:
	-del *.obj
	-del *.exe
	-del $(NAME).drv
	-del $(NAME).map
	-del $(NAME).sym
	-del display.map

	-del $(RES12DIR)\*.obj
	-del $(RES12DIR)\*.exe
	-del $(RES12DIR)\*.bin
	-del $(RES12DIR)\*.res
	-del $(RES12DIR)\*.mrk
	-del $(RES12DIR)\display.rcv

	-del $(RES16DIR)\*.obj
	-del $(RES16DIR)\*.exe
	-del $(RES16DIR)\*.bin