/* DPI毎のマルチリソース対応 */

#ifdef OEMRESOURCE

#define OBM_16_CLOSE	            34754 
#define OBM_16_UPARROW              34753 
#define OBM_16_DNARROW              34752 
#define OBM_16_RGARROW              34751 
#define OBM_16_LFARROW              34750 
#define OBM_16_REDUCE               34749 
#define OBM_16_ZOOM                 34748 
#define OBM_16_RESTORE              34747 
#define OBM_16_REDUCED              34746 
#define OBM_16_ZOOMD                34745 
#define OBM_16_RESTORED             34744 
#define OBM_16_UPARROWD             34743 
#define OBM_16_DNARROWD             34742 
#define OBM_16_RGARROWD             34741 
#define OBM_16_LFARROWD             34740 
#define OBM_16_MNARROW              34739 
#define OBM_16_COMBO                34738 
#define OBM_16_UPARROWI	            34737
#define OBM_16_DNARROWI	            34736
#define OBM_16_RGARROWI	            34735
#define OBM_16_LFARROWI	            34734

#define OBM_16_OLD_CLOSE            34767 
#define OBM_16_SIZE                 34766 
#define OBM_16_OLD_UPARROW          34765 
#define OBM_16_OLD_DNARROW          34764 
#define OBM_16_OLD_RGARROW          34763 
#define OBM_16_OLD_LFARROW          34762 
#define OBM_16_BTSIZE               34761 
#define OBM_16_CHECK                34760 
#define OBM_16_CHECKBOXES           34759 
#define OBM_16_BTNCORNERS           34758 
#define OBM_16_OLD_REDUCE           34757 
#define OBM_16_OLD_ZOOM             34756 
#define OBM_16_OLD_RESTORE          34755 

#define OCR_16_NORMAL               34512 
#define OCR_16_IBEAM                34513 
#define OCR_16_WAIT                 34514 
#define OCR_16_CROSS                34515 
#define OCR_16_UP                   34516 
#define OCR_16_SIZE                 34640 
#define OCR_16_ICON                 34641 
#define OCR_16_SIZENWSE             34642 
#define OCR_16_SIZENESW             34643 
#define OCR_16_SIZEWE               34644 
#define OCR_16_SIZENS               34645 
#define OCR_16_SIZEALL              34646 
#define OCR_16_ICOCUR               34647 

#define OIC_16_SAMPLE               34512 
#define OIC_16_HAND                 34513 
#define OIC_16_QUES                 34514 
#define OIC_16_BANG                 34515 
#define OIC_16_NOTE                 34516 

#endif /* OEMRESOURCE */
