#ifndef NPD_MODE_H
#define NPD_MODE_H

#define IDD_MAIN       100

#define IDC_WIDTH      101
#define IDC_HEIGHT     102
#define IDC_BPP        103

#define IDC_NP2_GROUP      104
#define IDC_NP2_USEGRAPH   105
#define IDC_NP2_USEDIB8    106
#define IDC_NP2_USEDIB8HC  107
#define IDC_NP2_MONOMODE_LUMA     108
#define IDC_NP2_MONOMODE_NONZERO  109
#define IDC_NP2_MONOMODE_DITHER   110
#define IDC_NP2_MONOLABEL         111

#endif
